package be.fp.distriWebApp.core.model.dto;
// Generated by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.apache.commons.lang3.builder.ToStringBuilder;


public class CocktailDto implements java.io.Serializable {

	private Integer id;
	private String intitule;
	private Float prix;
	private Integer color;

	private Set<IngredientcocktailDto> ingredientcocktails = new HashSet<IngredientcocktailDto>(0);

	public Integer getId() {
		return id;
	}
	
	public void setId(Integer id) {
		this.id = id;
	}
	public String getIntitule() {
		return intitule;
	}

	public void setIntitule(String intitule) {
		this.intitule = intitule;
	}

	public Float getPrix() {
		return prix;
	}

	public void setPrix(Float prix) {
		this.prix = prix;
	}

	public Integer getColor() {
		return color;
	}

	public void setColor(Integer color) {
		this.color = color;
	}

	public Set<IngredientcocktailDto> getIngredientcocktails() {
		return ingredientcocktails;
	}

	public void setIngredientcocktails(Set<IngredientcocktailDto> ingredientcocktails) {
		this.ingredientcocktails = ingredientcocktails;
	}


}
