package be.fp.distriWebApp.core.model.dto;
// Generated by Hibernate Tools 4.3.1.Final
import java.util.HashSet;
import java.util.Set;

import be.fp.distriWebApp.core.model.eo.Cocktail;

public class DistributeurDto implements java.io.Serializable {

	private int id;
	private CocktailDto cocktailEnCours;
	private RefLovsDto etat_lovs;
	private int numero;
	private String intitule;
	private String description;
	private String ipAdresse;
	private int portAtmega;
	private Set<DistricoktailtodoDto> districoktailtodos = new HashSet<DistricoktailtodoDto>(0);
	private Set<DistricoktaildispoDto> districoktaildispos = new HashSet<DistricoktaildispoDto>(0);
	private Set<PompeDto> pompes = new HashSet<PompeDto>(0);

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public RefLovsDto getEtat_lovs() {
		return etat_lovs;
	}

	public void setEtat_lovs(RefLovsDto etat_lovs) {
		this.etat_lovs = etat_lovs;
	}

	public int getNumero() {
		return numero;
	}

	public void setNumero(int numero) {
		this.numero = numero;
	}

	public String getIntitule() {
		return intitule;
	}

	public void setIntitule(String intitule) {
		this.intitule = intitule;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getIpAdresse() {
		return ipAdresse;
	}

	public void setIpAdresse(String ipAdresse) {
		this.ipAdresse = ipAdresse;
	}

	public int getPortAtmega() {
		return portAtmega;
	}

	public void setPortAtmega(int portAtmega) {
		this.portAtmega = portAtmega;
	}

	public Set<DistricoktailtodoDto> getDistricoktailtodos() {
		return districoktailtodos;
	}

	public void setDistricoktailtodos(Set<DistricoktailtodoDto> districoktailtodos) {
		this.districoktailtodos = districoktailtodos;
	}

	public Set<PompeDto> getPompes() {
		return pompes;
	}

	public void setPompes(Set<PompeDto> pompes) {
		this.pompes = pompes;
	}

	public Set<DistricoktaildispoDto> getDistricoktaildispos() {
		return districoktaildispos;
	}

	public void setDistricoktaildispos(Set<DistricoktaildispoDto> districoktaildispos) {
		this.districoktaildispos = districoktaildispos;
	}

	public CocktailDto getCocktailEnCours() {
		return cocktailEnCours;
	}

	public void setCocktailEnCours(CocktailDto cocktailEnCours) {
		this.cocktailEnCours = cocktailEnCours;
	}
	
}
