package be.fp.distriWebApp.core.model.dto;
// Generated by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.apache.commons.lang3.builder.ToStringBuilder;



public class DistricoktailtodoDto implements java.io.Serializable {

	public static final String ID = "id";
	public static final String COCKTAIL = "cocktail";
	public static final String PRIORITE = "priorite";


	private int id;
	private CocktailDto cocktail;
	private Integer priorite;

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public CocktailDto getCocktail() {
		return cocktail;
	}

	public void setCocktail(CocktailDto cocktail) {
		this.cocktail = cocktail;
	}

	public Integer getPriorite() {
		return priorite;
	}

	public void setPriorite(Integer priorite) {
		this.priorite = priorite;
	}


}
