package be.fp.distriWebApp.core.model.dto;
// Generated by Hibernate Tools 4.3.1.Final

public class DistricoktaildispoDto implements java.io.Serializable {



	private int id;
	private CocktailDto cocktail;
	private Float quantite;
	private Boolean actif;

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public CocktailDto getCocktail() {
		return cocktail;
	}

	public void setCocktail(CocktailDto cocktail) {
		this.cocktail = cocktail;
	}

	public Float getQuantite() {
		return quantite;
	}

	public void setQuantite(Float quantite) {
		this.quantite = quantite;
	}

	public Boolean getActif() {
		return actif;
	}

	public void setActif(Boolean actif) {
		this.actif = actif;
	}

}
