package be.fp.distriWebApp.core.model.dto;
// Generated by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;


public class IngredientDto implements java.io.Serializable {

	private Integer id;
	private PompeDto pompe;
	private String intitule;
	private boolean alcoolise;
	private Integer degreAlcool;
	private String marque;
	private BigDecimal quantitePleine;
	private BigDecimal quantiteRestante;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public PompeDto getPompe() {
		return pompe;
	}

	public void setPompe(PompeDto pompe) {
		this.pompe = pompe;
	}

	public String getIntitule() {
		return intitule;
	}

	public void setIntitule(String intitule) {
		this.intitule = intitule;
	}

	public boolean isAlcoolise() {
		return alcoolise;
	}

	public void setAlcoolise(boolean alcoolise) {
		this.alcoolise = alcoolise;
	}

	public Integer getDegreAlcool() {
		return degreAlcool;
	}

	public void setDegreAlcool(Integer degreAlcool) {
		this.degreAlcool = degreAlcool;
	}

	public String getMarque() {
		return marque;
	}

	public void setMarque(String marque) {
		this.marque = marque;
	}

	public BigDecimal getQuantitePleine() {
		return quantitePleine;
	}

	public void setQuantitePleine(BigDecimal quantitePleine) {
		this.quantitePleine = quantitePleine;
	}

	public BigDecimal getQuantiteRestante() {
		return quantiteRestante;
	}

	public void setQuantiteRestante(BigDecimal quantiteRestante) {
		this.quantiteRestante = quantiteRestante;
	}

}
