package be.fp.distriWebApp.core.model.dto;
// Generated by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;

public class IngredientcocktailDto implements java.io.Serializable {



	/**
	 * 
	 */
	private static final long serialVersionUID = 3402109015603525139L;
	private int id;
	private IngredientDto ingredient;
	private int numOrdre;

	private BigDecimal quantiteCl;

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}


	public IngredientDto getIngredient() {
		return ingredient;
	}

	public void setIngredient(IngredientDto ingredient) {
		this.ingredient = ingredient;
	}

	public int getNumOrdre() {
		return numOrdre;
	}

	public void setNumOrdre(int numOrdre) {
		this.numOrdre = numOrdre;
	}

	public BigDecimal getQuantiteCl() {
		return quantiteCl;
	}

	public void setQuantiteCl(BigDecimal quantiteCl) {
		this.quantiteCl = quantiteCl;
	}

}
