package be.fp.distriWebApp.core.model.dto;
// Generated by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.apache.commons.lang3.builder.ToStringBuilder;



public class PompeDto implements java.io.Serializable {



	private Integer id;
	private float debitmlperseconde;
	private String marque;
	private String typepompe;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public float getDebitmlperseconde() {
		return debitmlperseconde;
	}

	public void setDebitmlperseconde(float debitmlperseconde) {
		this.debitmlperseconde = debitmlperseconde;
	}

	public String getMarque() {
		return marque;
	}

	public void setMarque(String marque) {
		this.marque = marque;
	}

	public String getTypepompe() {
		return typepompe;
	}

	public void setTypepompe(String typepompe) {
		this.typepompe = typepompe;
	}

}
